"""Add product_code column to inventory table

Revision ID: 4aaa655ab562
Revises: 3267646aaa1e
Create Date: 2025-03-23 17:20:26.732918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aaa655ab562'
down_revision = '3267646aaa1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_code', sa.String(length=50), nullable=True))
        batch_op.alter_column('total_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint("uq_inventory_product_code", ["product_code"])  # Fix: Remove the extra argument
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint("uq_inventory_product_code", type_='unique')  # Use the same name to drop the constraint
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('product_code')
    # ### end Alembic commands ###
