"""Add stock_history table

Revision ID: d2db6a4eebce
Revises: bcb8866633db
Create Date: 2025-03-29 14:39:49.804153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text  # Import text for raw SQL queries


# revision identifiers, used by Alembic.
revision = 'd2db6a4eebce'
down_revision = 'bcb8866633db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing index if it exists
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_item_name')  # Drop the existing index
        batch_op.create_index(batch_op.f('ix_inventory_item_name'), ['item_name'], unique=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        # Check if the column already exists before adding it
        existing_columns = [row[1] for row in op.get_bind().execute(text("PRAGMA table_info(sale)")).fetchall()]
        if 'transaction_id' not in existing_columns:
            batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
            batch_op.create_index(batch_op.f('ix_sale_transaction_id'), ['transaction_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default="user"))
    op.alter_column('user', 'role', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_transaction_id'))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_name'))
    # ### end Alembic commands ###
